### ISSUE TITLE
Feature: Reshade Compability

### ISSUE THREAD

**Issue by retroluxfilm** [Detegr/openRBRVR#11]
First of thx for this great VR MOD for RBR. Works a lot better than the kegetys VR mod for me.
The only caveat is that I still can not get reshade to work with this mod. It crashes and I think its possibly due to DXVK and that reshade needs to get loaded at a earlier stage. The Iron Wolf managed to get it working for GTR2 by customly loading the reshade.dll at the right stage before dxvk hooks into d3d9 calls. 

I also tried to use the OpenXR mode with this mod and reshade but I did not manage to get it working here unfortunaly.

**Comment by dancek** [comment]
I've been looking into this for about a month now but no real luck yet. If you install in Vulkan mode it kinda works, but you only get the menu in the desktop window and when you change settings they only affect the VR image after restarting the game.

**Comment by retroluxfilm** [comment]
I just tried the latest version and now it works flawlessly in VR with the Reshade Vulkan mode through the reshade setup. Version 0.6 crashed before.  Well done!

The reshade dashboard in steamVR also works to the change the effects directly in VR . 2D and VR layers use each different reshade settings (Reshade.ini & ReshadeVR.ini) which explains that your changes you did in 2D where not directly visible in VR. In the old reshade version it just used one ini file for both and a restart had loaded the reshade settings also in VR. I can recommend you to try the VRToolkit shader to increase clarity.  https://vrtoolkit.retrolux.de/

**Comment by retroluxfilm** [comment]
Damn it still crashes when using the index, With the SteamVR null driver it worked. How did you get it working in vulkan mode?

**Comment by retroluxfilm** [comment]
With further testing I found out that it works when RBR is started before starting SteamVR. This results that reshade is able to hook into the rendering properly before VR is even started.  So a current workaround to get reshade working is to close steamVR and then start RBR with the VRMod enabled. (SteamVR will autostart then)

 I guess the VR initialization process in the VRMod is done too early in code. Properly initializing the 2D window before might fix that reshade will work regardless if SteamVR is already loaded or not. I attached you reshade logs where it works and where not. (It crashes when acessing the vrclient.dll) 

[ReShade_crashed.log](https://github.com/Detegr/openRBRVR/files/14136465/ReShade_crashed.log)
[ReShade_working.log](https://github.com/Detegr/openRBRVR/files/14136466/ReShade_working.log)

**Comment by Detegr** [comment]
Hi. The backlog for the project is such that supporting ReShade isn't on the top of the priority list for me at the moment. Of course if you're able to figure out changes that are needed for getting it to work I'm happy to include them.

I doubt the reason is too eager initialization, as the [VR initialization](https://github.com/Detegr/openRBRVR/blob/master/src/openRBRVR.cpp#L722-L730) is done after the Vulkan initialization at the moment. The `vrclient.dll` is however loaded at the start of the program, while in the working case it isn't, probably because SteamVR is not running. From the logs it seems that when it's working, `vrclient.dll` hooks are delayed, when in the crash log `vrclient.dll` is hooked right at the start of the process.

**Comment by dancek** [comment]
> The reshade dashboard in steamVR

Oh cool, so it does actually work! I never thought the settings would be hidden in some SteamVR menus. That's a bit annoying for usability but I guess I can live with that. I wonder where the configuration would be in OpenXR.

I consider the SteamVR crash a minor issue as there's a workaround and the crash seemed quite difficult to debug. Would be nice to get OpenXR working too (it crashes on startup), but realistically I don't think I'll be spending much time on this.

**Comment by dancek** [comment]
Also thanks for the link. The screenshot in https://vrtoolkit.retrolux.de/configuration.html really helped me figure out how to find the UI.

**Comment by retroluxfilm** [comment]
Glad that I at least could help to find a workaround. For me reshade sharpening is a gamechanger to reduce the blur on the Index. 
In OpenXR you need to configure it in the 2D window and then copy the reshade.ini and rename it reshadeVr.ini so your settins get picked up in VR as well after a restart of the game. The reshade dashbord only works through SteamVR right now.

Thanks @Detegr to pointing me to the init step. I  will try to work on a fix to get it working without the workaround right now and prepare a pull request if I manage to find a fix.  I think this will also help with OpenXR crash with reshade. But that I can not test as SteamVR does not support OpenXR in 32bit unfortunatly. 

Thanks again guys for the effort on this project. Amazing how professional it works with all the customizations to be able to set up etc.

**Comment by retroluxfilm** [comment]
Ok found the issue and added a pull request that fixes it.
