### ISSUE TITLE
Failed to initialize OpenXR: xrCreateInstance -9

### ISSUE THREAD

**Issue by dsieradzki** [Detegr/openRBRVR#14]
Hello I have HP Reverb G2 and I want to use OpenXR implementation but I get error from topic.

![openxruntime](https://github.com/Detegr/openRBRVR/assets/10297559/7336bb17-ffb0-48ca-afc2-174b61deff46)

**Comment by Detegr** [comment]
You probably noticed it yourself, but you're missing [OpenXR-Vk-D3D12](https://github.com/mbucchia/OpenXR-Vk-D3D12).
