### ISSUE TITLE
Not launching using Pimax 5KS after latest update. 

### ISSUE THREAD

**Issue by balamacab** [Detegr/openRBRVR#15]
The game is not starting after latest update using openxr or steamvr using a Pimax 5KS, even after reinstalling all content. 
there are no logs available even after enabling debugging. 
The pluging was working in the past.

**Comment by balamacab** [comment]
RBRVR does launch correctly.

**Comment by Detegr** [comment]
I think we diagnosed this in the openRBRVR Discord.
