### ISSUE TITLE
Game does not start

### ISSUE THREAD

**Issue by angelovzr** [Detegr/openRBRVR#7]
After running game crashes back to desktop and creates a dump file.

**Comment by Detegr** [comment]
Light plugin isn't compatible with this plugin. Please disable it. Also, sharing .dmp files publicly isn't a good idea as they contain information about your system. I edited your comment to remove link to it. For further diagnosing of startup issues, there is a Discord server for openRBRVR: https://discord.gg/tRJtuzRMvg
